### ISSUE TITLE
"Okay -->" button not clicking when hitting enter

### ISSUE THREAD

**Issue by Batcastle** [drauger-os-development/xfce4-desktop-service#1]
the "Okay -->" button in the two GUI windows should be clicked when hitting the "Enter" key.

This means setting the button in question as default in the necessary classes

However, attempting to do this either results in an error, or nothing.

**Comment by SenlisO** [comment]
Fixed by pull request #2 
I'll start looking into the other UIs which seem to need the same treatment but aren't referenced in this issue.

**Comment by SenlisO** [comment]
Will now apply fix to the two other UIs in this package

**Comment by Batcastle** [comment]
Fixed by #2
