### ISSUE TITLE
Consolidate "is directory" checking between signal_handler functions

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/xfce4-desktop-service#11]

**Comment by Batcastle** [comment]
Can you elaborate on this? Potentially show examples?

**Comment by SenlisO** [comment]
This was a comment I left myself a while back that it looked like there were multiple places where events are checking whether it is a directory.  Perhaps it could be refactored and streamlined, but nothing important to do right now.  Later, I will look more closely at this issue.
