### ISSUE TITLE
Fuzzy testing valueerror nullbyte exception for _custom_create_file

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/xfce4-desktop-service#14]
running fuzzy testing on custom_create_file causes the following crash:

```python
Traceback (most recent call last):
  File "/home/richard/.local/lib/python3.8/site-packages/pythonfuzz/fuzzer.py", line 24, in worker
    target(buf)
  File "test_create_file.py", line 17, in fuzz
    test_handler._custom_create_file("./test_files", test_name, False)
  File "/home/richard/Documents/xfce4-desktop-service/tests/xfce4_desktop_service.py", line 212, in _custom_create_file
    with open(parent_directory + "/" + file_name, "w+") as new_file:
ValueError: embedded null byte
crash was written to crash-13a4d91e94bf49aa9615e1d65631cd0c0ea0eeebd3022cd42a2fc8e7df9d46b5
crash = 0000dfae5d0000
```

The same thing happens in _rename method, but is currently being caught by handling a ValueError exception (simply printing the error to the console).

**Comment by Batcastle** [comment]
Has this issue been corrected? The commit referenced seems to fix the issue, unless it needs to be handled elsewhere too?

**Comment by SenlisO** [comment]
Just to confirm, is this fix included in the current ISO?

**Comment by Batcastle** [comment]
Yes. It should be in there.

**Comment by SenlisO** [comment]
The commits fixed the issue because if I go into Drauger and create a file named "00", the program doesn't crash .  However, the fuzzer is testing input to the _custom_create_file routine and not the GUI.  The fix is applied at the GUI level, so the fuzzer is still throwing exceptions.  I'll see if I can modify the fuzzer to test the GUI directly in the future.
