### ISSUE TITLE
Providing invalid input to filenames causes an exception to be thrown

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/xfce4-desktop-service#6]
Providing invalid input for a filename causes an unhanded exception.  An example is naming a file "Hello/World".
![can not create file](https://user-images.githubusercontent.com/13087164/110985744-ce744400-833a-11eb-8333-1ddb57c1bae1.png)

Additionally, providing invalid input for filenames can be processed, but then would not allow xfce4-desktop-service to interact with the file (such as deleting it).  An example would be "Hello>>World"
![trying to delete file](https://user-images.githubusercontent.com/13087164/110985861-f4014d80-833a-11eb-9d33-839f1dcd5183.png)

**Comment by Batcastle** [comment]
Did some research, we'll have to look into what other special characters do, but the only two characters we need to straight up REJECT should be the forward slash (`/`) and the `NUL` char (`\0`). 

Based on the last image in that issue, `>` converts to `%3E` so maybe it's getting returned as a bytes-like object and we need to `decode()` it?

**Comment by Batcastle** [comment]
Did some more research. `decode()` does not work, because the path is not a bytes-like object. It's a string encoded using percent encoding. We can use `urllib.parse.unquote()` to parse this out for us.

**Comment by SenlisO** [comment]
The recent commits fixes some invalid characters, not all.  The remaining unhanded exceptions I can generate are caused by "path traversal bugs", if I can coin that phrase.  Some examples: "Hello/World", "touch ../test.txt"

Creating a file from template throws an exception now.
![2021-03-15_05-43](https://user-images.githubusercontent.com/13087164/111133825-56cc3200-8551-11eb-957e-f4add34e4813.png)
This bug appears to be caused by commit "parse percent encoded paths" 02ff98e0d54d6abfb97d8b88f034482101d7cccc
```python
  source_files[each] = urllib.parse.unquote(source_files[each])
```

**Comment by Batcastle** [comment]
I think I got that new error fixed. It was a subtle one. There was a line I was editing the array paths where in, not the path itself.

**Comment by SenlisO** [comment]
Still need to test the previous fix.  Here is a new one

Creating an file with an empty name
![image](https://user-images.githubusercontent.com/13087164/111867277-506ef900-8949-11eb-985f-a58e081b7ab6.png)

Renaming a file with to empty name
![image](https://user-images.githubusercontent.com/13087164/111867300-71cfe500-8949-11eb-8d2c-afb9825c0bca.png)

Creating a directory with an empty name
![image](https://user-images.githubusercontent.com/13087164/111867327-975cee80-8949-11eb-97f8-a6d2c89119b6.png)

**Comment by Batcastle** [comment]
Thankfully that one's a pretty easy fix. Just a quick `if` statement. I should have a patch sometime today.

**Comment by Batcastle** [comment]
Alright. Did some quick testing and that last commit seems to have fixed the empty name bug.

**Comment by SenlisO** [comment]
I have been running the fuzzy-testing and this is one of the exceptions it seems to find most often:

```bash
Traceback (most recent call last):
  File "/home/richard/.local/lib/python3.8/site-packages/pythonfuzz/fuzzer.py", line 24, in worker
    target(buf)
  File "test_create_file.py", line 17, in fuzz
    test_handler._custom_create_file("./test_files", test_name, False)
  File "/home/richard/Documents/xfce4-desktop-service/tests/xfce4_desktop_service.py", line 212, in _custom_create_file
    with open(parent_directory + "/" + file_name, "w+") as new_file:
ValueError: embedded null byte
crash was written to crash-13a4d91e94bf49aa9615e1d65631cd0c0ea0eeebd3022cd42a2fc8e7df9d46b5
crash = 0000dfae5d0000
```

**Comment by SenlisO** [comment]
I tested the fixes for path traversal bugs and empty filename bugs and they both seem to be fixed.  However, if you want your errors to catch the attention of the user, perhaps using a different font than the rest of the UI would be helpful (red is a good example).  Another idea is to not allow the user to click the "okay" button if the filename is not valid, with an alt text that explains the filename is invalid.  I can work on those, just let me know what you think.

**Comment by SenlisO** [comment]
For clarity, broke out newest findings into their own issues
